# Generated by Django 4.2.18 on 2026-04-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Име')),
                ('source_type', models.CharField(choices=[('local', 'Local camera'), ('ip', 'IP camera / Stream URL')], default='local', max_length=20)),
                ('stream_url', models.URLField(blank=True, help_text='Остави празно при локална камера, ако ще се ползва device index.', null=True, verbose_name='Stream URL')),
                ('device_index', models.PositiveIntegerField(default=0, help_text='0 = default webcam', verbose_name='Device index')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('sensitivity_threshold', models.PositiveIntegerField(default=25, help_text='Колкото е по-ниско, толкова по-чувствителна е детекцията.', verbose_name='Праг на чувствителност')),
                ('min_area', models.PositiveIntegerField(default=500, help_text='Филтър срещу шум и дребни промени.', verbose_name='Минимална площ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Видео източник',
                'verbose_name_plural': 'Видео източници',
            },
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='Движение засечено', max_length=255)),
                ('frame_path', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='main.camerasource')),
            ],
            options={
                'verbose_name': 'Събитие при движение',
                'verbose_name_plural': 'Събития при движение',
                'ordering': ['-detected_at'],
            },
        ),
    ]
