# Generated by Django 4.2.18 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasource',
            name='stream_url',
            field=models.CharField(blank=True, help_text='Поддържа rtsp://, http:// или https:// адрес.', max_length=500, null=True, verbose_name='Stream URL'),
        ),
    ]
